version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development

      args:
        INSTALL_DEV: true
    volumes:
      - ./conduit/:/code
    ports:
      - 8000:8000
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - ${POSTGRES_DEFAULT_PORT}:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  # db1:
  #   image: postgres:15
  #   ports:
  #     - ${POSTGRES_SHARD1_PORT}:5432
  #   volumes:
  #     - ./.postgres:/var/lib/postgresql/data
  #   environment:
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
  #     - POSTGRES_USER=${POSTGRES_USER?Variable not set}
  #     - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  # db2:
  #   image: postgres:15
  #   ports:
  #     - ${POSTGRES_SHARD2_PORT}:5432
  #   volumes:
  #     - ./.postgres:/var/lib/postgresql/data
  #   environment:
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
  #     - POSTGRES_USER=${POSTGRES_USER?Variable not set}
  #     - POSTGRES_DB=${POSTGRES_DB?Variable not set}

volumes:
  .postgres:
  conduit:
