version: '3.8'

services:
  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/data/db:ro
      - media_volume:/data/media:ro
      - ./backups:/backups
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_S3_REGION_NAME}
      - BACKUP_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  postgres_data:
    external: true
  media_volume:
    external: true 