# Generated by Django 5.0.4 on 2024-05-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_user_created_at_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Name"),
        ),
    ]
