"""
Django settings for conduit project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from .base import *

DEBUG = False

DATABASES = {
    "default": {},
    "shard1": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", default="conduit"),
        "USER": os.getenv("POSTGRES_USER", default="conduit"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", default="conduit"),
        "HOST": os.getenv("POSTGRES_SHARD1_SERVER", default="localhost"),
        "PORT": os.getenv("POSTGRES_SHARD1_PORT", default="5432"),
    },
    "shard2": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", default="conduit"),
        "USER": os.getenv("POSTGRES_USER", default="conduit"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", default="conduit"),
        "HOST": os.getenv("POSTGRES_SHARD2_SERVER", default="localhost"),
        "PORT": os.getenv("POSTGRES_SHARD2_PORT", default="5432"),
    },
}

DATABASE_ROUTERS = ["config.database_routers.ShardRouter"]
