# Generated by Django 5.0.4 on 2024-05-13 04:34

from django.conf import settings
from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):

    dependencies = [
        ("conduit_articles", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["created"], name="articles_ar_created_e6d39d_idx"),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=CASCADE,
                related_name="published_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
