# Generated by Django 5.0.4 on 2024-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_metadata_alter_article_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
    ]
