# Generated by Django 5.1.6 on 2025-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduit_articles', '0006_alter_article_options_remove_article_article_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
